/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ComponentShape = "sharp" | "rounded" | "soft" | "pill";

/**
 * العقد الموحد الوحيد بين الويزارد والديمو. أي تعديل في شكل الكونفيج يتم هنا فقط، ثم يُعاد توليد TypeScript types في الويزارد والديمو من هذا الملف نفسه.
 */
export interface ProjectConfigInput {
  /**
   * معرّف المشروع الفريد
   */
  id: string;
  /**
   * اسم المشروع
   */
  projectName: string;
  /**
   * عنوان التاب في المتصفح
   */
  websiteTitle: string;
  /**
   * Hex أو rgb، مثال #D94452
   */
  primaryColor: string;
  /**
   * SVG خام للوجو
   */
  logoSvg?: string;
  /**
   * نسخة dark mode من اللوجو
   */
  logoSvgDark?: string;
  /**
   * قرار مُتخذ: تمت إضافته من ProjectConfig (runtime) لأنه كان ناقصًا من ProjectConfigInput.
   */
  faviconSvg?: string;
  /**
   * قرار مُتخذ: تمت إضافته من ProjectConfig (runtime) للسبب نفسه.
   */
  isDefault?: boolean;
  colors?: ProjectColorConfig;
  style?: ProjectStyleConfig;
  domains: ConfigInputDomain[];
}
/**
 * قرار مُتخذ: تُركت top-level (مطابقة لما يعمل فعليًا في project-config.service.ts الحالي)، ولم تُنقل تحت style، رغم أن الكومنت الأصلي في الكود كان يقترح ذلك.
 */
export interface ProjectColorConfig {
  /**
   * Seed hex يقود الـ PrimeNG palette
   */
  primary?: string;
  light?: ColorZoneTokens;
  dark?: ColorZoneTokens;
}
export interface ColorZoneTokens {
  topbarBg?: string;
  topbarColor?: string;
  topbarBorder?: string;
  topbarShadow?: string;
  sidebarBg?: string;
  sidebarActiveColor?: string;
  bodyBg?: string;
  bodyColor?: string;
  textOverride?: string;
  cardBg?: string;
  cardBorder?: string;
  cardShadow?: string;
  dialogHeaderBg?: string;
  dialogHeaderColor?: string;
  dialogBorder?: string;
  dialogShadow?: string;
  tableHeaderBg?: string;
  tableHoverBg?: string;
  accentOverride?: string;
}
export interface ProjectStyleConfig {
  table?: TableStyleConfig;
  dialog?: DialogStyleConfig;
  card?: CardStyleConfig;
  topbar?: TopbarStyleConfig;
  sidebar?: SidebarStyleConfig;
  button?: ButtonStyleConfig;
  login?: LoginStyleConfig;
}
export interface TableStyleConfig {
  style?: "default" | "striped" | "bordered" | "minimal";
  headerStyle?: "filled" | "gradient" | "minimal";
  rowSeparator?: "none" | "thin" | "thick" | "colored";
  columnSeparator?: boolean;
  rowHeight?: "compact" | "normal" | "spacious";
  shape?: ComponentShape;
  advanced?: ComponentStyleConfig;
}
export interface ComponentStyleConfig {
  cornerRadius: number;
  elevationShadow: boolean;
  width: "standard" | "highlighted";
  internalPadding: number;
  border: boolean;
  borderWidth: number;
  borderColor: string;
  externalMargin: number;
  fontFamily: string;
  fontWeight: "Regular" | "Medium" | "Bold";
  subElements: {
    [k: string]: SubElementStyle;
  };
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^(title|body|footer|header|row|content)$".
 */
export interface SubElementStyle {
  fontFamily: string;
  fontSize: number;
  fontWeight: "Regular" | "Medium" | "Bold";
  fontColor: string;
  textAlign: "left" | "center" | "right" | "justify";
}
export interface DialogStyleConfig {
  style?: "flat" | "accent-header" | "gradient-header" | "outlined";
  headerHeight?: "compact" | "normal" | "tall";
  overlayOpacity?: "light" | "medium" | "dark";
  animation?: "fade" | "slide" | "zoom";
  shape?: ComponentShape;
  advanced?: ComponentStyleConfig;
}
export interface CardStyleConfig {
  style?: "elevated" | "bordered" | "flat" | "glass";
  shape?: ComponentShape;
  advanced?: ComponentStyleConfig;
}
/**
 * قرار مُتخذ: بدون advanced — topbar لسه مش ComponentKey معترف بيه في ui-style-designer (tables|sidebars|cards|dialogs|shapes بس).
 */
export interface TopbarStyleConfig {
  height?: "compact" | "normal" | "tall";
  border?: "none" | "thin" | "shadow";
  logoStyle?: "icon-text" | "icon-only" | "text-only" | "hidden";
  navAlign?: "left" | "center" | "right";
  navStyle?: "links" | "pills" | "underline" | "buttons";
  showLang?: boolean;
  showTheme?: boolean;
  showConfig?: boolean;
  showSearch?: boolean;
  showNotif?: boolean;
}
export interface SidebarStyleConfig {
  width?: "narrow" | "normal" | "wide";
  iconsOnly?: boolean;
  advanced?: ComponentStyleConfig;
}
/**
 * قرار مُتخذ: بدون advanced — button لسه مش ComponentKey مستقل، وممكن يتقابل مع shapes لاحقًا.
 */
export interface ButtonStyleConfig {
  size?: "sm" | "md" | "lg";
  shadow?: "none" | "soft" | "lifted";
  shape?: ComponentShape;
}
export interface LoginStyleConfig {
  layout?: "centered" | "split" | "fullscreen";
  bg?: "solid" | "gradient" | "image";
  bgColor?: string;
  bgGradientFrom?: string;
  bgGradientTo?: string;
  logoPos?: "top" | "left" | "hidden";
}
export interface ConfigInputDomain {
  id: string;
  label: string;
  enabled?: boolean;
  modules: ConfigInputModule[];
}
export interface ConfigInputModule {
  id: string;
  label: string;
  icon?: string;
  apiUrl: string;
  fallbackJsonAr?: string;
  fallbackJsonEn?: string;
  idField?: string;
  actions?: {
    create?: boolean;
    edit?: boolean;
    view?: boolean;
    delete?: boolean;
  };
  enabled?: boolean;
  subModules?: ConfigInputSubModule[];
}
export interface ConfigInputSubModule {
  id: string;
  label: string;
  icon?: string;
  /**
   * مثال: /org/communities
   */
  path: string;
  enabled?: boolean;
}
